### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by fennectech** [darkenvy/Minecraft-Vita-Pack-Creator#2]
[fennectech@Titanium ~/PSMinecraft-Resource-Converter]$  node main.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'gm'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fennectech/PSMinecraft-Resource-Converter/main.js:2:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by psiie** [comment]
Make sure to `npm install` before using the `node main.js` command. main.js uses the gm library.

Oh, Im going to guess that you do not have imagemagick installed through brew. So you may need these additonal steps. This installs system-wide and allows you do use them in further applications:

`brew install imagemagick` to install imagemagick
If you do not have brew installed, visit [http://brew.sh/](http://brew.sh/)

**Comment by fennectech** [comment]
{18:54} Mon Dec 19
[fennectech@Titanium ~/.bin]$  sudo pacman -S imagemagick
[sudo] password for fennectech: 
warning: imagemagick-6.9.6.7-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) imagemagick-6.9.6.7-1

Total Installed Size:  9.93 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] n

**Comment by fennectech** [comment]
i dont have npm and im installing brew on my linux box now

**Comment by fennectech** [comment]
[fennectech@Titanium ~/.bin]$  brew install imagemagick
Error: Permission denied @ rb_file_s_symlink - (/lib64/ld-linux-x86-64.so.2, /usr/local/lib/ld.so)

**Comment by psiie** [comment]
Brew is for OSX. I'm not sure how well **gm** will recognize an install of imagemagick on linux. So don't be surprised if it doesn't work when you get to that point.

I don't have a linux machine on me, but I can look into this later on this week if you don't get it solved. Be sure to lookup 'how to install imagemagick on linux'. Then install NPM and nodejs.

**Comment by psiie** [comment]
Linux setup
–––––––––––
1. Install NPM
2. Install NodeJS
3. Install ImageMagick
4. NPM Install
5. node main.js
6. Profit

**Comment by fennectech** [comment]
[fennectech@Titanium ~/PSMinecraft-Resource-Converter]$  node main.js 
/home/fennectech/PSMinecraft-Resource-Converter/main.js:44
    let userDir = __dirname + '/import/' + dir + '/assets/minecraft/textures/' + shortDirectory;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by fennectech** [comment]
[fennectech@Titanium ~]$  npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.8.14-1-MANJARO
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /home/fennectech/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/home/fennectech/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fennectech/npm-debug.log

**Comment by psiie** [comment]
I don't think you are in the right directory. It's looking for package.json at /home/fennectech/package.json. IF you extract the zip, the directory should look more like: /home/fennectech/PSMinecraft-Resource-Converter/package.json

**Comment by psiie** [comment]
I'm looking into compiling this into a standalone app. This was just cooked up in my normal environment. Stay posted. I'm still invested & making updates.
